#!/bin/sh
##########################################################################
# If not stated otherwise in this file or this component's LICENSE
# file the following copyright and licenses apply:
#
# Copyright 2016 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################################################################
PATH=/usr/local/bin:/usr/bin:/bin:/sbin:/usr/sbin

# PlatCo does not support an sd card so there is nothing to do here.

start_function()
{
    echo nothing to do 
}


stop_function()
{
    echo nothing to do
}


## Main App ##
#--------------
case $1 in
    "start")
        echo "Calling start_function()"
        start_function
        ;;
   "stop")
        echo "Calling stop_function()"
        stop_function
        ;;
   "restart")
        echo "Calling restart_function()"
        stop_function
        start_function
        ;;
    *)

      echo "Usage: $0 {start|stop|restart}"
      ;;
esac



