#
# SubTtxRend-App configuration file, used by TextTrack.
#

#
# Teletext font setting
#
RDKENV.FEATURE.TTX.FONT.G0.NAME = Teletext 43
TELETEXT.FONT_G0_G2.NAME = Teletext 43

# Force TTML font, overrides fontFamily in content
TTML.FORCE_FONT = Cinecav Sans
# Force WebVTT font, overrides content
WEBVTT.FONT.FAMILY = Cinecav Sans

# - Message levels enabled configuration
#
# LOGGER.LEVELS_DEFAULT = FATAL ERROR WARNING INFO
# LOGGER.LEVELS.<component> = levels
# LOGGER.LEVELS.<component>.<element> = levels
# levels = ALL FATAL ERROR WARNING INFO DEBUG TRACE
#
# To enable level and all more important levels use level name with '+'
# character at the end e.g. "INFO+" (means INFO WARNING ERROR FATAL).
#
LOGGER.LEVELS_DEFAULT = WARNING+
# CORE.INFO has some possibly useful logging to check that services are running
LOGGER.LEVELS.CORE = INFO+
# Actual subtitles are logged as INFO. We don't want those by default.
# LOGGER.LEVELS.REND = INFO+
