BBPATH .= ":${LAYERDIR}"

BBFILES += "\
            ${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend \
           "

BBFILE_COLLECTIONS += "video"
BBFILE_PATTERN_video := "^${LAYERDIR}/"
BBFILE_PRIORITY_video = "7"
LAYERSERIES_COMPAT_video = "zeus dunfell kirkstone"

# license directories.
LICENSE_PATH += "${LAYERDIR}/licenses"


RDKCENTRAL_GITHUB_ROOT ?= "git://github.com/rdkcentral"
RDKCENTRAL_GITHUB_PROTOCOL ?= "https"
RDKCENTRAL_GITHUB_SRC_URI_SUFFIX ?= "protocol=${RDKCENTRAL_GITHUB_PROTOCOL};nobranch=1"

require conf/distro/include/rdk_video_lto.inc
