BBPATH .= ":${LAYERDIR}"

BBFILES += "\
            ${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend \
           "

BBFILE_COLLECTIONS += "video"
BBFILE_PATTERN_video := "^${LAYERDIR}/"
BBFILE_PRIORITY_video = "7"
LAYERSERIES_COMPAT_video = "zeus dunfell kirkstone"

# license directories.
LICENSE_PATH += "${LAYERDIR}/licenses"

require conf/distro/include/rdk_video_lto.inc

# Remove WPE-WebKit from the build
DISTRO_FEATURES:remove = "webkitbrowser-plugin"

BBMASK .= "|meta-rdk-video/recipes-extended/wpe-webkit"
BBMASK .= "|meta-rdk/recipes-extended/webkitbrowser-plugin"
BBMASK .= "|meta-rdk/recipes-core/packagegroups/packagegroup-wpe-webkit"
BBMASK .= "|meta-rdk-video/recipes-extended/rdk-browserlauncher"
BBMASK .= "|meta-rdk/recipes-extended/wpe-backend-rdk"
BBMASK .= "|meta-rdk-sky/recipes-sky/recipes-extended/browserlauncher/browserlauncher.bb"
BBMASK .= "|meta-rdk-sky/recipes-sky/recipes-extended/browserlauncher/browserlauncher.inc"
BBMASK .= "|meta-rdk-sky/recipes-sky/recipes-extended/browserwidget"

# Remove AAMP from the build
BBMASK .= "|meta-rdk-video/recipes-extended/aamp"
BBMASK .= "|meta-rdk-comcast-video/recipes-qt/aamp"

# Remove Fog from the build (unbreakable dependency on aamp)
BBMASK .= "|meta-rdk-restricted/recipes-extended/fog"
BBMASK .= "|meta-rdk-comcast-video/recipes-extended/fog"
