# CMake system name must be something like "Linux".
# This is important for cross-compiling.

set( CMAKE_SYSTEM_NAME Linux )
set( CMAKE_SYSTEM_PROCESSOR arm )
set( CMAKE_C_COMPILER arm-rdk-linux-gnueabi-gcc )
set( CMAKE_CXX_COMPILER arm-rdk-linux-gnueabi-g++ )
set( CMAKE_C_COMPILER_LAUNCHER  )
set( CMAKE_CXX_COMPILER_LAUNCHER  )
set( CMAKE_ASM_COMPILER arm-rdk-linux-gnueabi-gcc )
find_program( CMAKE_AR arm-rdk-linux-gnueabi-gcc-ar DOC "Archiver" REQUIRED )

set( CMAKE_C_FLAGS " -march=armv7ve -mthumb -mfpu=neon -mfloat-abi=hard        --sysroot=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0/recipe-sysroot  -Os -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0=/usr/src/debug/entservices-deviceanddisplay/1.1.4-r0                      -fdebug-prefix-map=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0=/usr/src/debug/entservices-deviceanddisplay/1.1.4-r0                      -fdebug-prefix-map=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0/recipe-sysroot-native=  -Wno-deprecated-declarations" CACHE STRING "CFLAGS" )
set( CMAKE_CXX_FLAGS " -march=armv7ve -mthumb -mfpu=neon -mfloat-abi=hard        --sysroot=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0/recipe-sysroot  -Os -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0=/usr/src/debug/entservices-deviceanddisplay/1.1.4-r0                      -fdebug-prefix-map=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0=/usr/src/debug/entservices-deviceanddisplay/1.1.4-r0                      -fdebug-prefix-map=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0/recipe-sysroot-native=  -Wno-deprecated-declarations -fvisibility-inlines-hidden  -I/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0/recipe-sysroot/usr/include/wdmp-c/   -I/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0/recipe-sysroot/usr/include/trower-base64/   -DRFC_ENABLED   -DNET_DEFINED_INTERFACES_ONLY -DNET_NO_LINK_LOCAL_ANNOUNCE   -Wall -Werror " CACHE STRING "CXXFLAGS" )
set( CMAKE_ASM_FLAGS " -march=armv7ve -mthumb -mfpu=neon -mfloat-abi=hard        --sysroot=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0/recipe-sysroot  -Os -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0=/usr/src/debug/entservices-deviceanddisplay/1.1.4-r0                      -fdebug-prefix-map=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0=/usr/src/debug/entservices-deviceanddisplay/1.1.4-r0                      -fdebug-prefix-map=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0/recipe-sysroot-native=  -Wno-deprecated-declarations" CACHE STRING "ASM FLAGS" )
set( CMAKE_C_FLAGS_RELEASE "-DNDEBUG" CACHE STRING "Additional CFLAGS for release" )
set( CMAKE_CXX_FLAGS_RELEASE "-DNDEBUG" CACHE STRING "Additional CXXFLAGS for release" )
set( CMAKE_ASM_FLAGS_RELEASE "-DNDEBUG" CACHE STRING "Additional ASM FLAGS for release" )
set( CMAKE_C_LINK_FLAGS " -march=armv7ve -mthumb -mfpu=neon -mfloat-abi=hard        --sysroot=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0/recipe-sysroot  -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fmacro-prefix-map=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0=/usr/src/debug/entservices-deviceanddisplay/1.1.4-r0                      -fdebug-prefix-map=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0=/usr/src/debug/entservices-deviceanddisplay/1.1.4-r0                      -fdebug-prefix-map=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0/recipe-sysroot-native=   -Wl,--no-as-needed -ltelemetry_msgsender -Wl,--as-needed   -Wl,-z,relro  " CACHE STRING "LDFLAGS" )
set( CMAKE_CXX_LINK_FLAGS " -march=armv7ve -mthumb -mfpu=neon -mfloat-abi=hard        --sysroot=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0/recipe-sysroot  -Os -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0=/usr/src/debug/entservices-deviceanddisplay/1.1.4-r0                      -fdebug-prefix-map=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0=/usr/src/debug/entservices-deviceanddisplay/1.1.4-r0                      -fdebug-prefix-map=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0/recipe-sysroot-native=  -Wno-deprecated-declarations -fvisibility-inlines-hidden  -I/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0/recipe-sysroot/usr/include/wdmp-c/   -I/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0/recipe-sysroot/usr/include/trower-base64/   -DRFC_ENABLED   -DNET_DEFINED_INTERFACES_ONLY -DNET_NO_LINK_LOCAL_ANNOUNCE   -Wall -Werror  -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fmacro-prefix-map=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0=/usr/src/debug/entservices-deviceanddisplay/1.1.4-r0                      -fdebug-prefix-map=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0=/usr/src/debug/entservices-deviceanddisplay/1.1.4-r0                      -fdebug-prefix-map=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0/recipe-sysroot-native=   -Wl,--no-as-needed -ltelemetry_msgsender -Wl,--as-needed   -Wl,-z,relro  " CACHE STRING "LDFLAGS" )

# only search in the paths provided so cmake doesnt pick
# up libraries and tools from the native build machine
set( CMAKE_FIND_ROOT_PATH /home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0/recipe-sysroot /home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0/recipe-sysroot-native     /home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/hosttools)
set( CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY )
set( CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY )
set( CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY )
set( CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY )
set( CMAKE_PROGRAM_PATH "/" )

# Use qt.conf settings
set( ENV{QT_CONF_PATH} /home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0/qt.conf )

# We need to set the rpath to the correct directory as cmake does not provide any
# directory as rpath by default
set( CMAKE_INSTALL_RPATH  )

# Use RPATHs relative to build directory for reproducibility
set( CMAKE_BUILD_RPATH_USE_ORIGIN ON )

# Use our cmake modules
list(APPEND CMAKE_MODULE_PATH "/home/akulka799/ATHIRA_TEST/rdke-stack/build-xione-uk/tmp-debug/work/xione-uk-middleware-rdk-linux-gnueabi/entservices-deviceanddisplay/1.1.4-r0/recipe-sysroot/usr/share/cmake/Modules/")

# add for non /usr/lib libdir, e.g. /usr/lib64
set( CMAKE_LIBRARY_PATH /usr/lib /lib)

# add include dir to implicit includes in case it differs from /usr/include
list(APPEND CMAKE_C_IMPLICIT_INCLUDE_DIRECTORIES /usr/include)
list(APPEND CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES /usr/include)

