[Unit]
# Broadcom-only 
ConditionPathExists=/sys/class/net/wl0.2

Requires=sys-subsystem-net-devices-wl0.2.device
After=sys-subsystem-net-devices-wl0.2.device
Requires=wpa_supplicant.service
After=wpa_supplicant.service

[Service]
ExecStartPost=

ExecStartPre=
ExecStartPre=/bin/sh -c 'source /usr/bin/wlan-p2p.sh'
ExecStartPre=/bin/sh -c '/usr/bin/wl02-p2p.sh'
