# Broadcom only drop-in conf file
[Unit]
ConditionPathExists=/sys/class/net/wl0.2
Requires=sys-subsystem-net-devices-wl0.2.device
After=sys-subsystem-net-devices-wl0.2.device

Requires=wpa_supplicant.service
After=wpa_supplicant.service


